### ISSUE TITLE
digdeeper/spyware.neocities.org

### ISSUE THREAD

**Issue by smnthermes** [PolishFiltersTeam/KADhosts#37] opened 2020-12-13 14:18 UTC
digdeeper.neocities.org and spyware.neocities.org aren't fake news websites:
https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADfakeHosts.txt

**Comment by hawkeye116477** [comment] 2020-12-13 15:00
It was already discussed and they are talking about things which they aren't fully understand and extrapolating a lot of things. 
For example, I can't agree that self updating is spyware. They are a bit too paranoid.

Anyway, it's duplicate of https://github.com/PolishFiltersTeam/KADhosts/issues/26.

**Comment by potatosareyummy** [comment] 2020-12-13 18:58
Well I have a few things to respond to if I may.

> https://github.com/PolishFiltersTeam/KADhosts/issues/37
> I can't agree that self updating is spyware.

	The spyware website openly states on the front page of the site that it defines spyware as any request sent without the consent or knowledge of the user. The website takes a consequentialist approach when it comes to issues like this because when it comes to measuring the functionality of the browser, It isn't that useful to look at business ethics of the developers. Because we're measuring the functionality of the browser, which is the whole point of the website.
	Even if a consequentialist approach to software is objectively false, the website's definition of spyware would merely be hyperbolic, which would mean that the site shows a bias, not that it spreads misinformation. Take the highly credible but yet left-leaning news outlet Democracy Now when it for example writes an article on the rise of fascism. This article goes through all of the policies that Trump is in favor of. You can make the case that say at least half of the policies that was listed in the article weren't fascist ones (or if all of them in this example weren't, but were instead just standard neoconservative policies). This would not show that the data is false, at best it would show the inference of the data is isn't that well thought out (the inference of the data is an opinion, the data itself is the information). This would make the news outlet show a left wing bias, not that it spreads misinformation. You could say the same thing with the spyware website. The fact that the inference of the data at hand is hyperbolic would show that my site has a Richard Stallman-like bias. Not that it spreads misinformation.

> https://github.com/MrAlex94/Waterfox/issues/1264
> For example, Waterfox must know which is operating system and version to provides updates.

	I think this is a clear cut example of misrepresenting what the website is all about. Giving a rational for why a connection is made doesn't change the fact that that the connection was made to begin with. You will find that most (all?) developers give a rational for why they make their software create requests without the consent of the user. Which is another reason why it's not useful to try to find the motives behind why software is as it is, rather it's best to just look at the software as it is.

> https://github.com/MrAlex94/Waterfox/issues/1264
>  I mean they seem to link previous reddit threads, but are extrapolating a lot of points and making up theories.

	I agree with the fact that using Reddit threads alone shouldn't be used as a source of information. I think though both you and I can agree though that the an exception can be made when a developer is communicating via Reddit. Both cases of using Reddit as a source of in formation in the Waterfox article were instances of quoting what the developers have said.
	This isn't that I don't make mistakes though. I make mistakes a lot. Which is why you're more than welcome to make a pull request here if I do make a mistake: [](https://codeberg.org/shadow/SpywareWatchdog). I hope that this clears things up and I hope you can remove the spyware website from your hosts file. Even if you still think that my site is "fake news", it isn't unreasonable for people to think that you're pushing the boundaries of what it is to be fake news. Thank you for your time in reading this && have a nice day.

- Baobab

*Full disclaimer, I run the spyware website*

**Comment by hawkeye116477** [comment] 2020-12-13 21:12
If software is open-source then you could look at it's code, analyze, check it. In my opinion, you are abusing „spyware" word.

**Comment by krystian3w** [comment] 2020-12-14 11:16
Or change type of block from broken page to only uBlock0 / AdGuard warming:

```
||digdeeper.neocities.org^$document
||spyware.neocities.org^$document
```

**Comment by potatosareyummy** [comment] 2020-12-14 18:02
Well... I didn't think I would actually get this far.

I would like to make a few quick more points if I may.

>If software is open-source then you could look at it's code, analyze, check it.

I agree that libre software is awesome! I think all software should be libre. Although, my values that make myself come to the conclusion that libre software is amazing are the same values that would make myself reject requests without the consent of the user (mainly the value of control over your own life). I'm not saying that libre software is a bad idea, rather that it doesn't go far enough.

>In my opinion, you are abusing "spyware" word.

I don't want to debate the word that much, but I'll quickly respond to this point. Originally, I based my definition of spyware from my Merriam-Webster's Dictionary. There is an online version here: https://www.merriam-webster.com/dictionary/spyware. The reason why I added the consent part to my definition is because suddenly knowing that your application is spyware doesn't make it any less spyware. The reason why I dropped the part where it just shows the installation aspect without consent/knowledge is that there are plenty of software that both you and I agree that's installed with the consent of the user that's still spyware (WebDiscover is even blocked my most antivirus software last I checked). The reason why I brought up why I define the way I define spyware is to show that I didn't merely pull that definition out of thin air. This point that I'm making here doesn't have to do with if my site is fake news or not, but I just wanted to show my thought process behind my definition to clear things up.

My point is that if it is true that malicious intent with the requests is a requirement for spyware to be spyware, it doesn't expose my site as being fake news, it just exposes my site as having a bias due to being hyperbolic with the definition of spyware. You can say that bias is by definition fake news, but I think that pushed the boundaries of what is to be fake news so far that most news outlets (including the very credible ones) would be fake news 24/7. I personally don't think that's a very efficient way of using that definition.

>These are great theories... When I leave the house, a tree will fall and I'll broke the leg...

Well I probably should have been more specific with that passage, but my intention isn't to make a theory that Waterfox does in fact bundle spyware in the updates (I don't know that it does, I haven't used the browser through multiple versions to see). My point was to show the some of the potential downsides of updates that are automatic. You can make the similar comparison to libre software. Although the fact that a program is non-libre software alone doesn't make it spyware, but it can be used as a tool to aid spyware. I would say the same case can be made about updates that are automatic. My real reason why I think auto updating is bad is because it takes control away from the user and into the hands of the developers, which I believe is a mistake. I know Firefox has a _very_ bad habit of doing this. It always seems like whenever I update my Firefox's version, I have to redo my user.js for all of the changes. A quick example of a program that through updates makes the browser worse for privacy is Firefox. Firefox has a _very_ bad habit of doing this. It always seems like whenever I update my Firefox's version, I have to redo my user.js for all of the changes that were made!

>https://web.archive.org/web/20201124112952/https://spyware.neocities.org/articles/waterfox.html
>This is especially likely to happen (that Waterfox uses auto updates to make the program more spyware-like).

Looking back on the article, the website shouldn't of have speculated this way. During winter break, I'll remove that part from the article and try to make that section in the article more clear (I'm finishing my first semester of college right now as of the moment). Although I think that the speculation that I've made shouldn't have been made in the article, I would argue that that would show a bias, not that it's fake news. As I have said before, I do make mistakes a lot and that would be an example of a mistake that I've made. I'll actually quickly change that right now.

Thank you for your time in reading this and I hoped this helps clear things up. Have a nice day!

-- Baobab

**Comment by qorg11** [comment] 2020-12-15 19:12
As the other spyware website maintainer, i approve the message above

**Comment by potatosareyummy** [comment] 2020-12-23 03:19
Wow, I can't believe that actually worked. Thank you @hawkeye116477 for hearing me out.

**Closed** 2020-12-23 08:54 UTC
Labels: question
